# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: System.Debug
  value: true
- name: PesterVersion
  value: 4.10.1
- name: csvTemplates
  value: subscription.json,networking/hub-region.v0.json,networking/hub-region.v1.json,networking/hub-region.v2.json,networking/spoke-BU0001A0005-00.json,networking/spoke-BU0001A0005-01.json,cluster-stamp.json,cluster-stamp.v2.json

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: armTemplateToolkit
  displayName: Validate ARM Assets
  jobs:
    - job: armttk
      displayName: Run ARM TTK
      pool:
        vmImage: 'windows-latest'
      continueOnError: false
      timeoutInMinutes: 4
      steps:
      - task: PowerShell@2
        displayName: Download Pester Test Runner
        inputs:
          targetType: inline
          script: |
            Invoke-RestMethod -Uri https://raw.githubusercontent.com/mspnp/samples/master/tests/Test.ARMTemplate.ps1 -OutFile (New-Item -Path "$env:PIPELINE_WORKSPACE\tests\Test.ARMTemplate.ps1" -Force)
      - task: PowerShell@2
        displayName: Install ARM TTK
        inputs:
          targetType: inline
          script: |
            git clone https://github.com/Azure/arm-ttk.git $env:PIPELINE_WORKSPACE\arm-ttk
      - task: PowerShell@2
        displayName: Install Pester
        inputs:
          targetType: inline
          script: |
            Install-Module Pester -AllowClobber -RequiredVersion $(PesterVersion) -Force -SkipPublisherCheck -AcceptLicense -Scope CurrentUser
      - task: PowerShell@2
        displayName: Execute ARM-TTK & Pester
        inputs:
          targetType: inline
          script: |
            Import-Module Pester -RequiredVersion $(PesterVersion) -ErrorAction Stop
            Import-Module $env:PIPELINE_WORKSPACE\arm-ttk\arm-ttk\arm-ttk.psd1 -ErrorAction Stop
            $counter = 1
            "$(csvTemplates)".split(",") | ForEach {
              Invoke-Pester -Script @{Path = "$env:PIPELINE_WORKSPACE\tests\Test.ARMTemplate.ps1"; Parameters = @{TemplatePath = "$_"; Skip = ""}} -OutputFormat NUnitXml -OutputFile $("{0:000}-ARMTemplate.xml" -f $counter) -PassThru
              $counter += 1
            }
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: NUnit
          mergeTestResults: true
          testResultsFiles: '*-ARMTemplate.xml'
        condition: always()
