# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: System.Debug
  value: true

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: armTemplateToolkit
  jobs:
    - job: armttk
      pool:
        vmImage: 'windows-latest'
      continueOnError: false
      timeoutInMinutes: 4

      steps:
      - task: PowerShell@2
        displayName: Install ARM TTK
        inputs:
          targetType: 'inline'
          script: |
            git clone https://github.com/Azure/arm-ttk.git --quiet $env:PIPELINE_WORKSPACE\arm-ttk
            import-module $env:PIPELINE_WORKSPACE\arm-ttk\arm-ttk
      - task: PowerShell@2
        displayName: Install Pester
        inputs:
          targetType: 'inline'
          script: |
            Install-Module Pester -AllowClobber -RequiredVersion 4.10.1 -Force -SkipPublisherCheck -AcceptLicense
            Import-Module Pester -RequiredVersion 4.10.1 -ErrorAction Stop
          
      - task: PowerShell@2
        displayName: Execute ARM-TTK & Pester
        inputs:
          targetType: 'inline'
          script: |
            Install-Module Pester -AllowClobber -RequiredVersion 4.10.1 -Force -SkipPublisherCheck -AcceptLicense
            Import-Module Pester -RequiredVersion 4.10.1 -ErrorAction Stop

            $results = Invoke-Pester -Script @{Path = "$(System.DefaultWorkingDirectory)$(pester-script-location)"; Parameters = @{TemplatePath = "$(System.DefaultWorkingDirectory)$(template-location)$(template-name)"; Skip = "$(ttk-skip-test)"}} -OutputFormat NUnitXml -OutputFile TEST-ARMTemplate.xml -PassThru
            if ($results.TestResult.Result -contains "Failed") {Write-Error -Message "Test Failed"}
      
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: TEST-ARMTemplate.xml
        condition: always()
