# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: System.Debug
  value: true
- name: PesterVersion
  value: 4.10.1

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: armTemplateToolkit
  displayName: Validate ARM Assets
  jobs:
    - job: armttk
      displayName: Validate ARM Assets
      pool:
        vmImage: 'windows-latest'
      continueOnError: false
      timeoutInMinutes: 4
      steps:
      - task: PowerShell@2
        displayName: Download Pester Test Runner
        inputs:
          targetType: inline
          script: |
            Invoke-RestMethod -Uri https://raw.githubusercontent.com/mspnp/samples/master/tests/Test.ARMTemplate.ps1 -OutFile (New-Item -Path "$env:PIPELINE_WORKSPACE\tests\Test.ARMTemplate.ps1" -Force)
      - task: PowerShell@2
        displayName: Install ARM TTK
        inputs:
          targetType: inline
          script: |
            git clone https://github.com/Azure/arm-ttk.git $env:PIPELINE_WORKSPACE\arm-ttk
      - task: PowerShell@2
        displayName: Install Pester
        inputs:
          targetType: inline
          script: |
            Install-Module Pester -AllowClobber -RequiredVersion $(PesterVersion) -Force -SkipPublisherCheck -AcceptLicense -Scope CurrentUser
      - task: PowerShell@2
        displayName: Execute ARM-TTK & Pester
        inputs:
          targetType: inline
          script: |
            Import-Module Pester -RequiredVersion $(PesterVersion) -Verbose -ErrorAction Stop
            Import-Module $env:PIPELINE_WORKSPACE\arm-ttk\arm-ttk\arm-ttk.psd1 -Verbose -ErrorAction Stop
            Invoke-Pester -Script @{Path = "$env:PIPELINE_WORKSPACE\tests\Test.ARMTemplate.ps1"; Parameters = @{TemplatePath = "$(System.DefaultWorkingDirectory)\subscription.json"; FilesSkip = ""}} -OutputFormat NUnitXml -OutputFile subscription-ARMTemplate.xml -PassThru
            Invoke-Pester -Script @{Path = "$env:PIPELINE_WORKSPACE\tests\Test.ARMTemplate.ps1"; Parameters = @{TemplatePath = "$(System.DefaultWorkingDirectory)\subscription.json"; FilesSkip = ""}} -OutputFormat NUnitXml -OutputFile subscription2-ARMTemplate.xml -PassThru
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: NUnit
          mergeTestResults: true
          testResultsFiles: '*-ARMTemplate.xml'
        condition: always()
